### ISSUE TITLE
'usbfind' appears to be console based, but 'objbrowser' depends on QT.

### ISSUE THREAD

**Issue by mungewell** [Merimetso-Code/USB-Hacking#1]
It seems that objbrowser has a dependancy on QT and will not run without it....
```
C:\Users\swood\Downloads\USB-Hacking-main-20220124>"c:\Program Files\Python310\python.exe" usbfind.py
Traceback (most recent call last):
  File "C:\Users\swood\Downloads\USB-Hacking-main-20220124\usbfind.py", line 12, in <module>
    from objbrowser import browse
ModuleNotFoundError: No module named 'objbrowser'

C:\Users\swood\Downloads\USB-Hacking-main-20220124>"c:\Program Files\Python310\python.exe" usbfind.py
Traceback (most recent call last):
  File "c:\Program Files\Python310\lib\site-packages\objbrowser\__init__.py", line 18, in <module>
    import qtpy.QtCore as _QtCore
  File "c:\Program Files\Python310\lib\site-packages\qtpy\QtCore.py", line 42, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'

  The following packages are required to run objbrowser:
      six
      PySide or PyQt

  Could not run objbrowser because: No module named 'PyQt5'
Traceback (most recent call last):
  File "C:\Users\swood\Downloads\USB-Hacking-main-20220124\usbfind.py", line 12, in <module>
    from objbrowser import browse
ImportError: cannot import name 'browse' from 'objbrowser' (c:\Program Files\Python310\lib\site-packages\objbrowser\__init__.py)
```

I acquired objbrowser with
```
C:\WINDOWS\system32>"c:\Program Files\Python310\python.exe" -m pip install objbrowser
Collecting objbrowser
  Downloading objbrowser-1.3.0.zip (31 kB)
  Preparing metadata (setup.py) ... done
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting qtpy
  Downloading QtPy-2.0.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 260 kB/s
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 2.7 MB/s
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.7-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 2.4 MB/s
Using legacy 'setup.py install' for objbrowser, since package 'wheel' is not installed.
Installing collected packages: pyparsing, packaging, six, qtpy, objbrowser
    Running setup.py install for objbrowser ... done
Successfully installed objbrowser-1.3.0 packaging-21.3 pyparsing-3.0.7 qtpy-2.0.0 six-1.16.0
```

**Comment by OpM3TA** [comment]
Yeah, Idk whats going on in this script, but I think objbrowser was used during development of the script, so he could get a view of pyusbs objects to later walk them with pyusb.

Then, when it came time to upload, he just stripped all the "testing" code, but left the import in, maybe just in case, or maybe because he forgot what it was even for.

But all i know is the code after the import, does not use the imported module, so that line can just be discarded/deleted, and the pip package removed.

Edit: Hi guy from 4 years ago, Jesus
